apiVersion: v1
kind: Service
metadata:
    name: svc-galaxyazuredevopskuberneteslinuxclient
    labels:
        product: galaxyazuredevopskuberneteslinuxclient
spec:
    selector:
        app: app-galaxyazuredevopskuberneteslinuxclient
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: dep-galaxyazuredevopskuberneteslinuxclient
spec:
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: app-galaxyazuredevopskuberneteslinuxclient
        spec:
            containers:
            - image: galaxyjpjc.azurecr.io/galaxyazuredevopskuberneteslinuxclient:__Build.BuildId__
              imagePullPolicy: IfNotPresent
              name: galaxyazuredevopskuberneteslinuxclient
              ports:
              - containerPort: 80
            imagePullSecrets:
            - name: regsecret